### PR TITLE
Add  `open_collection()` and add `to_zarr()` to Collection

### PR DESCRIPTION
**Pull request by mgrover1**
A first step towards enabling saving/reading in collections

- [x]  Borrow from zarr's approach of writing a consolidated metadata file (`.xcollection.json`). This  "special" JSON file would be written in the root directory and will contain a list of "valid" keys/paths of xarray datasets within that root directory. This allows us to avoid listing everything within the root directory. 
- [x] Add `.to_zarr(self, directory, **kwargs)` method. `directory` would point to the root directory that contains `.xcollection.json` file
- [x]  Add `.to_netcdf(self, directory, *, mode: str = 'w', **kwargs)` method 
- [x] `xc.open_collection(directory, **kwargs)`  function: if `directory` doesn't contain `.xcollection.json` file, we raise an error and exit. 
- [x] BONUS: make this functionality file-system agnostic via `fsspec`.

### CODE REVIEW

**Comment by mgrover1** [comment]
@andersy005 here it is! Feel free to leave comments/suggestions

**Comment by mgrover1** [comment]
@andersy005 I was able to implement all of those except for `fsspec`...

**Comment by mgrover1** [comment]
@andersy005 should we wait to review until I implement `fsspec`?

**Comment by andersy005** [comment]
@mgrover1, my latest commit includes changes we discussed during last week's meeting. With these changes, I expect this to work with any `fsspec` compatible store.

**Comment by mgrover1** [comment]
Thanks @andersy005 !!

**Pull request merged**
