### PR TITLE
Add Weighted Method to Collection Object

### LINKED ISSUE #14: Add weighted() function
One card on the Trello board is to add `weighted.mean()` method to the Collection object.  On the [Xarray Documentation](https://xarray.pydata.org/en/stable/generated/xarray.core.weighted.DatasetWeighted.html) I see that we have 4 similar functions (`weighted()`, `weighted.mean()`, `weighted.sum()`, and `weighted.sum_of_weights()`). 

In practice it seems that `mean()` is just called on an already weighted object. Do we want to add some sort of Decorator to a Collection object to indicate that it is weighted - or just allow someone to call `mean` on anything?

Also I am designing the function to go through every dataset in the collection, and create a collection of weighted datasets. I think this is the intended behavior (we're not trying to combine the different datasets here).

### PR DESCRIPTION
**Pull request by jukent**
Funnel work with @mnlevy1981 

Closes #14

### CODE REVIEW

**Comment by jukent** [comment]
[Add weighted.mean to Collection](https://trello.com/c/sMKTQapN/19-add-weightedmean-to-collection)

**Comment by jukent** [comment]
This takes a `Collection` of `Datasets`, and a`DataArray` of `weights`, to create a `CollectionWeighted` (i.e. collection of weighted `Datasets` - this class inherits from the `xarray.Weighted`) upon which `.mean()`, `.sum()`, and `'sum_of_weights` can be called (anything that can be called on a `DatasetWeighted` item).

What is the best use case for this? What I want to understand is if a scientist would use different weights on different `Datasets`? @matt-long

**Comment by kmpaul** [comment]
@jukent: I don't know how the weighting works.  For example, if you are weighting a DataArray object, do the weights need to have the same dimensions/coordinates as the DataArray object itself?  For Datasets, do the weights need to have the same dimensions/coordinates as are in the Dataset?  

If the answer to those questions is "yes," then I am concerned that weighting will not work (naively) for Collections.  What if the Datasets don't all have the same dimensions/coordinates?  How do you apply the weights?

**Comment by jukent** [comment]
> @jukent: I don't know how the weighting works. For example, if you are weighting a DataArray object, do the weights need to have the same dimensions/coordinates as the DataArray object itself? For Datasets, do the weights need to have the same dimensions/coordinates as are in the Dataset?
> 
> If the answer to those questions is "yes," then I am concerned that weighting will not work (naively) for Collections. What if the Datasets don't all have the same dimensions/coordinates? How do you apply the weights?

Yes I'm 99% sure the answer to those questions is yes, since each weight is associated with a different data value. I think the target is to allow users to weight collections of datasets of the same size in one call, and have the call fail if any of the datasets are the wrong size. This is what this PR does so far, but it could use some more checks to make it more robust.

2 other ideas: Add a test that the dimensions match the weights and skip any Dataset that isn't the right shape. And from @mnlevy1981 was to add a list that points to which collections we'd like to weight. Still in the end both of those objects give us a collection of weighted and unweighted objects that doesn't fit neatly into either Collection class.

**Comment by matt-long** [comment]
I could see use cases where a user might want to compute global or regional means on datasets that have different grids. In this case, the weights would be different for each dataset. 

It seems to me that one primary use case for collections is to handle instances where you want to apply operations to multiple datasets that cannot or should not be concatenated along a (possibly new) dimension.

**Comment by jukent** [comment]
Thanks @matt-long for your reply and insight. 

I'll make a dictionary of 'weights' DataArrays with keys mapping to every dataset in the collection, and then the dictionary is an input arg for the 'weighted()' function.

**Comment by kmpaul** [comment]
@jukent:  I think that's too complicated of a solution.  I don't think people should be expected to know the grid of every dataset.  I guess that's the expectation of Xarray's `Dataset.weighted`, but I wonder if multiple datasets is just getting too complicated or setting too high of a bar for users.  ...Otherwise, what benefit is it for Xcollection to have a `weighted` method if you have to deal with every dataset individually anyway?

What about interpolation?  Is that safe to do?

**Comment by jukent** [comment]
Can we discuss this during the Xdev team time today?

**Comment by kmpaul** [comment]
I say go ahead and discuss it.  I'm sorry, but I can't make it.  We can talk tomorrow, if you prefer.

**Comment by matt-long** [comment]
I think this is an instance of where coupling a `collection` with a framework for tracking dataset metadata might be useful. For example, one could imagine selecting the appropriate weights field on the basis of information about the dataset stored in an `intake-esm` catalog.

**Comment by kmpaul** [comment]
Please keep in mind that the `DataTree` work that @dcherian mentioned is happening in Xarray could completely replace Xcollection.  And probably will, considering how far along it is.  I think Xcollection should focus on implementing the capabilities that we need for a funnel prototype.  That's it.

**Comment by dcherian** [comment]
>  Xcollection should focus on implementing the capabilities that we need for a funnel prototype

:+1: perhaps the trello board should be updated to track core functions that are really needed to exercise that prototype.

**Review by kmpaul — APPROVED** [review]
@jukent:  I think this looks good.  Let's go ahead and merge it and then we can add more if this doesn't suffice for the Funnel prototype.

**Pull request merged**
